- filename: DBLP.bib
  search_type: FEED
  source_name: Information Systems Journal
  source_url: ''
  search_parameters:
  - endpoint: dblp
    params: SCOPE venue_key='journals/isj' AND journal_abbreviated='Inf. Syst. J.'
  last_sync: null
  comment: ''
- filename: CROSSREF.bib
  search_type: FEED
  source_name: CROSSREF
  source_url: CROSSREF.bib
  search_parameters: ''
  last_sync: null
  comment: ''
