- filename: DBLP.bib
  search_type: FEED
  source_name: Information Systems Journal
  source_url: ''
  search_parameters:
  - endpoint: dblp
    params: SCOPE venue_key='journals/isj' AND journal_abbreviated='Inf. Syst. J.'
  last_sync: null
  comment: ''
- filename: CROSSREF.bib
  search_type: FEED
  source_name: CROSSREF
  source_url: CROSSREF.bib
  search_parameters: ''
  last_sync: null
  comment: ''
- filename: pdfs.bib
  search_type: FEED
  source_name: ISJ
  source_url: pdfs
  search_parameters:
  - endpoint: pdfs_directory
    params: SCOPE path='pdfs' WITH journal='Information Systems Journal' AND sub_dir_pattern='volume_number'
  comment: NA
